# reference
# [1] https://matplotlib.org/stable/api/matplotlib_configuration_api.html#matplotlib.rcParams
# [2] https://matplotlib.org/stable/users/explain/customizing.html
[data]
sample_hap = 'hap_groups.csv' # a csv file with the haplotype frequencies
sample_group = 'sample_groups.csv' # a csv file with the sample group information

[plot]
group_index = 1 # 0-based index of the column in the sample_group_csv file that contains the group names
name = 'hastat_bar.png' # can be 'hastat_bar.png' or 'hastat_bar.pdf'
x_label = 'Haplotype'
y_label = 'Haplotype frequency'
